### PR TITLE
fix: Multisite: use get_current_blog_id() instead of $wpdb->blogid

### LINKED ISSUE #742: Multisite: use get_current_blog_id() instead of $wpdb->blogid
See https://core.trac.wordpress.org/ticket/41684#comment:12

### PR DESCRIPTION
**Pull request by thepriefy**
get_current_blog_id() is more appropriate for determining the ID of the current site in most cases.
This eliminates the need for the global $wpdb in several functions and is better than the implicit
global used in admin pages.

Closes #742

### CODE REVIEW

File: src/components/points/includes/class-wordpoints-points-logs-query.php [hunk 1]
```diff
@@ -162,7 +162,7 @@ class WordPoints_Points_Logs_Query extends WordPoints_DB_Query {
 	 *        @type string       $text__compare       Comparison operator for $text. May be any of these:  '=', '<>', '!=', 'LIKE', 'NOT LIKE'. Default is 'LIKE'.
 	 *        @type string[]     $text__in            Return only logs with these texts.
 	 *        @type string[]     $text__not_in        Exclude logs with these texts from the results.
-	 *        @type int          $blog_id             Limit results to those from this blog within the network (multisite). Default is $wpdb->blogid (current blog).
+	 *        @type int          $blog_id             Limit results to those from this blog within the network (multisite). Default is get_current_blog_id() (current blog).
```
Comment (JDGrimes) [inline src/components/points/includes/class-wordpoints-points-logs-query.php]: Here we can just change the sentence to:

>Default is the current blog (or 0 if not on multisite).

File: src/components/ranks/classes/user/ranks/query.php [hunk 2]
```diff
@@ -74,7 +74,7 @@ class WordPoints_User_Ranks_Query extends WordPoints_DB_Query {
 	 *        @type string       $rank_group__compare The comparison operator to use with the above value.
 	 *        @type string[]     $rank_group__in      A list of rank groups to query for.
 	 *        @type string[]     $rank_group__not_in  A list of rank groups to exclude.
-	 *        @type int          $blog_id             Limit results to those from this blog within the network (multisite). Default is $wpdb->blogid (current blog).
+	 *        @type int          $blog_id             Limit results to those from this blog within the network (multisite). Default is get_current_blog_id() (current blog).
```
Comment (JDGrimes) [inline src/components/ranks/classes/user/ranks/query.php]: Same can be done here as with the other comment.

File: tests/phpunit/tests/ranks/update/2-4-0-alpha-4.php [hunk 3]
```diff
@@ -189,7 +189,7 @@ public function test_update_user_ranks_table_duplicates() {
 				'user_id'    => (string) $user_id,
 				'rank_id'    => (string) $another_rank_id,
 				'rank_group' => 'points_type-points',
-				'blog_id'    => is_multisite() ? (string) $wpdb->blogid : '0',
+				'blog_id'    => is_multisite() ? (string) get_current_blog_id() : '0',
```
Comment (JDGrimes) [inline tests/phpunit/tests/ranks/update/2-4-0-alpha-4.php]: This can be left as you have it now, because it already uses the multisite conditional.

File: tests/phpunit/tests/ranks/update/2-4-0-alpha-4.php [hunk 4]
```diff
@@ -201,7 +201,7 @@ public function test_update_user_ranks_table_duplicates() {
 				'user_id'    => (string) $user_id,
 				'rank_id'    => (string) $third_rank_id,
 				'rank_group' => 'points_type-points',
-				'blog_id'    => is_multisite() ? (string) $wpdb->blogid : '0',
+				'blog_id'    => is_multisite() ? (string) get_current_blog_id() : '0',
```
Comment (JDGrimes) [inline tests/phpunit/tests/ranks/update/2-4-0-alpha-4.php]: This one also already uses the multisite conditional, so it is also good like you have made it now.

**Comment by thepriefy** [comment]
@JDGrimes I have already done what you had requested but the test still fail. Do you know why?

**Comment by JDGrimes** [comment]
@thepriefy Just ignore the Scrutinizer tests, I haven't got Scrutinizer working properly right now. In fact, I have just disabled it for PRs to avoid confusion.

It looks like most of the tests are passing on Travis now, so that is good. The remaining failures there don't look to be related to this change. I will take care of them after I merge your PR. It looks like it is ready to go, so I will merge shortly. Thank you!
